version: 2.1
orbs:
  docker: circleci/docker@2.4.0

jobs:
  verify:
    docker:
      - image: ghcr.io/graalvm/jdk:ol8-java17-22.3.1
    steps:
      - checkout
      - run:
          name: Code Verification
          command: ./mvnw verify -DskipTests

  test:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Start mysql test db
          command: |
            docker images
            docker run -d --name test-db -e MYSQL_ROOT_PASSWORD=rootadmin -e MYSQL_DATABASE=user-test -p 3306:3306 mysql:latest
      - run:
          name: Run Unit Tests
          command: ./mvnw test
      - store_test_results:
          path: target/surefire-reports

  build_and_push_image:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - docker/check:
          docker-password: REGISTRY_PASSWORD
          docker-username: REGISTRY_USER
          registry: ${DOCKER_REGISTRY}
      - run:
          name: Start mysql test db
          command: |
            docker images
            docker run -d --name test-db -e MYSQL_ROOT_PASSWORD=rootadmin -e MYSQL_DATABASE=user-test -p 3306:3306 mysql:latest
      - run:
          name: Build Image
          command: |
            ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${DOCKER_REGISTRY}/${REGISTRY_USER}/user-service:<< pipeline.number >>_${CIRCLE_SHA1}
      - docker/push:
          image: ${REGISTRY_USER}/user-service
          tag: << pipeline.number >>_${CIRCLE_SHA1}
          registry: ${DOCKER_REGISTRY}

  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - add_ssh_keys:
          fingerprints: ["9b:c3:18:8c:43:0e:5e:1e:05:73:e4:5c:57:84:ec:99"]
      - run:
          name: checkout helm chart repository
          command: |
            git clone git@github.com:Cypherfund/helm-charts.git -b main
            cd helm-charts && ls -la
      - run:
          name: update values file
          command: |
              cd helm-charts
              sed -i "s/tag:.*/tag: ${CIRCLE_SHA1}/g" tech-ascend-charts/user-service/values.yaml
              cat tech-ascend-charts/user-service/values.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
     - verify
     - test
     - build_and_push_image:
         requires:
         - test
         - verify
     - deploy:
        requires:
        - build_and_push_image
        filters:
          branches:
            only: main
